# Generated by Django 4.0.3 on 2022-03-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
